server:
  port: 8082
logging:
  config: classpath:spring-logback.xml
spring:
  application:
    name: hongda-server

    # 配置数据源
  datasource:
    # 配置数据类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.96.234.82:3306/practice_study?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  # 打印mybatis的sql日志


# 配置justauth 第三方登录
justauth:
  enabled: true
  type:
    GITEE:
      client-id: 61977df44510af284a0af469e00bb7d04e71bca90071498e3a950afa9b7cfc66
      client-secret: 629a042c918264063890e7f184851b964d60c6bfb043bef1b67b129be961c8b0
      redirect-uri: http://127.0.0.1:8082/oauth/gitee/callback
  cache:
    type: default

# 配置mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml







# 常量
myapp:
  name: first-project
  version: 1.0.0



