server:
  port: 8082
logging:
  config: classpath:spring-logback.xml
spring:
  application:
    name: hongda-server

    # 配置数据源
  datasource:
    # 配置数据类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.96.234.82:3306/practice_study?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host:  47.96.234.82
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-idle: 16
        min-idle: 8
        max-active: 32


# 配置文件上传
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB




# 配置mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml


# 配置justauth 第三方登录
justauth:
  enabled: true
  type:
    GITEE:
      client-id: 61977df44510af284a0af469e00bb7d04e71bca90071498e3a950afa9b7cfc66
      client-secret: 629a042c918264063890e7f184851b964d60c6bfb043bef1b67b129be961c8b0
      redirect-uri: http://127.0.0.1:8082/oauth/gitee/callback
  cache:
    type: default




# 设置上传路径
upload:
  folder: D:/file/
  download: /download?fileName=


# 常量
myapp:
  name: first-project
  version: 1.0.0



